# Identificadores de tu proyecto en SonarQube
sonar.projectKey=Juan-3-punto-14-16_Prices-Off
sonar.organization=juan-3-punto-14-16
sonar.projectName=Prices-Off

# ¿Dónde está el código fuente que quieres evaluar? (Separado por comas)
sonar.sources=paginaWeb
sonar.exclusions=paginaWeb/tests/**

# ¿Dónde están tus pruebas?
sonar.tests=paginaWeb/tests
sonar.coverage.exclusions=paginaWeb/includes/app.php,paginaWeb/includes/database.php,paginaWeb/public/index.php,paginaWeb/src/**,paginaWeb/views/**

# El puente de cobertura: Aquí le decimos dónde buscar el archivo clover.xml
sonar.php.coverage.reportPaths=paginaWeb/clover.xml
