# Identificadores de tu proyecto en SonarQube
sonar.projectKey=Juan-3-punto-14-16_Prices-Off
sonar.projectName=Prices-Off

# ¿Dónde está el código fuente que quieres evaluar? (Separado por comas)
sonar.sources=controllers,includes,jobs,models,public,views,Router.php

# ¿Dónde están tus pruebas?
sonar.tests=tests

# El puente de cobertura: Aquí le decimos dónde buscar el archivo clover.xml
sonar.php.coverage.reportPaths=clover.xml
