name: Pest -> SonarQube

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  analisis:
    name: Ejecutar Pest y SonarQube
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: robot
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: test_pricesoff
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    defaults:
      run:
        working-directory: paginaWeb

    steps:
      # 1. El servidor descarga tu código
      - name: Descargar código
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Necesario para que SonarQube entienda el historial

      # 2. El servidor instala PHP con los "lentes" de XDEBUG
      - name: Instalar PHP y Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" 
          coverage: xdebug

      # 3. Instalamos las dependencias de Composer (incluyendo Pest)
      - name: Instalar Composer
        working-directory: paginaWeb
        run: composer install --prefer-dist --no-progress

      - name: Preparar Base de Datos de Pruebas
        run: PGPASSWORD=password123 psql -h localhost -U robot -d test_pricesoff -f tests/db_test_seed.sql

      - name: Crear archivo JSON de Google
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDENTIALS_JSON }}
        run: echo "$GCP_CREDS" > paginaWeb/google-credenciales.json

      - name: Crear archivo .env temporal
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=test_pricesoff" >> .env
          echo "DB_USER=robot" >> .env
          echo "DB_PASS=password123" >> .env
          echo "GOOGLE_GEOCODING_API_KEY=${{ secrets.GOOGLE_GEOCODING_API_KEY }}" >> .env
          echo "DOCUMENT_AI_PROCESSOR_ID=${{ secrets.DOCUMENT_AI_PROCESSOR_ID }}" >> .env
          echo "GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}" >> .env
          echo "GOOGLE_CLOUD_LOCATION=${{ secrets.GOOGLE_CLOUD_LOCATION }}" >> .env
          echo "GOOGLE_APPLICATION_CREDENTIALS=google-credenciales.json" >> .env

      # 4. ¡LA MAGIA! Corremos las pruebas y generamos el archivo temporal clover.xml
      - name: Ejecutar Pest PHP y generar Cobertura
        working-directory: paginaWeb
        run: vendor/bin/pest --coverage --coverage-clover=clover.xml

      # 5. SonarQube lee el clover.xml y manda los resultados a la nube
      - name: Escaneo de SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
